name: first workflow # name of the workflow
on: workflow_dispatch # Event - how to execute this workflow
jobs:
  first-job: # job name
    runs-on: ubuntu-latest
    steps:
     - name: print hello
       run: echo "Hello"
     - name: print bye
       run: echo "good bye!"
